name: Automated Version Updates

on:
  schedule:
    - cron: '0 2 * * *'  # Every day at 2:00 UTC
  workflow_dispatch:

jobs:
  update-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Run update scripts
        run: |
          cd scripts
          python3 update_nginx.py
          python3 update_wordpress.py
          python3 update_apache_httpd.py
          python3 update_php.py
          python3 update_apache_tomcat.py
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ../current_versions.json
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "Automated update of current_versions.json"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "Automated update of current_versions.json"
          title: "Automated update of current_versions.json"
          body: "This PR was created automatically by a scheduled GitHub Actions workflow."
          branch: "auto/update-versions"
          base: ${{ github.ref_name }}
          add-paths: ../current_versions.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
